app/blueprints/account/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, HiddenField
from wtforms.validators import DataRequired
from wtforms.widgets import HiddenInput



class PokeDataForm(FlaskForm):
    poke_name = HiddenField(validators=[DataRequired()])
    submit = SubmitField()

app/blueprints/account/__init__.py
from flask import Blueprint

bp = Blueprint('account', __name__, template_folder='templates')

from . import routes

app/blueprints/account/routes.py
from flask import render_template, flash, redirect, url_for, g, request
from flask_login import login_required, current_user

from . import bp as account
from app import app
from app.blueprints.account.forms import PokeDataForm
from app.models import User, Pokedex, Team, TeamPokemon
from app.blueprints.account.helper import get_dict_info_pokemon, get_all_pokemon_dict


@app.before_request
def before_request():
    g.poke_data_form = PokeDataForm()


@account.route('/account/<username>')
@login_required
def home(username):
    user = User.query.filter_by(username=username).first()
    if user:
        return render_template('account.jinja', user=user, search_form=g.search_form, pokedex=user.pokedex, poke_data_form=g.poke_data_form)
    else:
        flash(f'User: {username} not found', category='warning')
        return redirect(url_for('main.home', search_form=g.search_form, poke_data_form=g.poke_data_form))


@account.route('/search/<search>', methods=['GET', 'POST'])
@login_required
def general_search(search):
    search = search.strip()
    count = 0
    user = User.query.filter_by(username=search).first()
    if not user:
        user = None
    else:
        count = Pokedex.query.filter_by(user_id=user.id).count()
    search = search.lower()
    pokemon = get_all_pokemon_dict()
    if search in pokemon.keys():
        poke_dict = get_dict_info_pokemon(search)
    else: 
        poke_dict = None
    return render_template('general_search.jinja',pokemon=poke_dict, user=user, search=search, search_form=g.search_form, count=count, poke_data_form=g.poke_data_form)

@account.post('/search-form')
@login_required
def form_search():
    search = g.search_form.search.data
    return redirect(url_for('account.general_search', search=search))


@account.post('/add-to-pokedex')
@login_required
def add_to_pokedex():
    if g.poke_data_form.validate_on_submit():
        pokemon = g.poke_data_form.poke_name.data
    if pokemon not in [poke.name for poke in current_user.pokedex]:
        try:
            poke_info = get_dict_info_pokemon(pokemon)
            pe = Pokedex()
            pe.user_id = current_user.id
            pe.name = poke_info['name']
            pe.pokemon_id = poke_info['pokemon_id']
            pe.height = poke_info['height']
            pe.weight = poke_info['weight']
            pe.base_exp = poke_info['base_exp']
            pe.sprite = poke_info['sprite']
            pe.types = ', '.join(poke_info['types'])
            pe.pick_rand_moves(list(poke_info['moves'].keys()))
            pe.commit()
            flash(f'{pokemon.title()} has been added to your PokeDex.', category='success')
            return redirect(url_for('account.home', username=current_user.username,search_form=g.search_form, poke_data_form=g.poke_data_form))
        except:
            flash(f'{pokemon.title()} is already in your PokeDex or does not exist.', category='warning')
            return redirect(url_for('account.home', username=current_user.username, search_form=g.search_form,  poke_data_form=g.poke_data_form))
    else:
        flash(f'{pokemon.title()} is already in your PokeDex or does not exist.', category='warning')
        return redirect(url_for('account.home', username=current_user.username, search_form=g.search_form,  poke_data_form=g.poke_data_form))
    
    

    
    
    

app/blueprints/account/templates/account.jinja
{% extends "base.jinja" %}
{% block content %}
  <h1>{{user.username.title()}} Home Page</h1>
  <div class="d-flex flex-row flex-wrap">
  {% for pokemon in pokedex %}
  <div class="card" style="min-width: 15rem; width: 15rem;">
    <img src="{{ pokemon.sprite }}" class="card-img-top">
    <div class="card-body">
      <h5 class="card-title">{{ pokemon.name.title() }}</h5>
      <p class="card-text">Pokemon Id: {{ pokemon.pokemon_id }}</p>
      <p class="card-text">Pokemon Height: {{ pokemon.height }}</p>
      <p class="card-text">Pokemon Weight: {{ pokemon.weight }}</p>
      <p class="card-text">Pokemon Types: {{ pokemon.types }}</p>
      <form action="" method="POST" novalidate>
        {{ poke_data_form.poke_name(value=pokemon.name) }}
        {{ poke_data_form.hidden_tag() }}
        <div class="d-flex justify-content-end">
          {{ poke_data_form.submit(class="btn btn-mint fw-medium text-dark m-1", value='Remove from PokeDex') }}
        </div>
      </form>
    </div>
  </div>
  {% endfor%}
  </div>
{% endblock content %}

app/blueprints/account/templates/general_search.jinja
{% extends "base.jinja" %}
{% block content %}
<h1>General User and Pokemon search page</h1>
<hr>
<div class="d-flex justify-content-evenly align-items-center flex-row">
  {% if user %}
  <div class="m-2">
    <h2>User Search</h2>
    <hr>
    <div class="card" style="width: 18rem;">
      <img src='../../../static/images/default_profile_pic.png' class="card-img-top">
      <div class="card-body">
        <h5 class="card-title">{{ user.username }}</h5>
        <p class="card-text">PokeDex pokemon count {{ count }}/1281</p>
        <a href="{{ url_for('account.home', username=user.username) }}" class="btn btn-mint">Go to their profile page</a>
      </div>
    </div>
  </div>
  {% endif %}
  {% if pokemon %}
  <div class="m-2">
    <h2>Pokemon Search</h2>
    <hr>
    <div class="card" style="width: 18rem;">
      <img src="{{ pokemon['sprite'] }}" class="card-img-top">
      <div class="card-body">
        <h5 class="card-title">{{ pokemon['name'].title() }}</h5>
        <p class="card-text">Pokemon Id: {{ pokemon['pokemon_id'] }}</p>
        <p class="card-text">Pokemon Height: {{ pokemon['height'] }}</p>
        <p class="card-text">Pokemon Weight: {{ pokemon['weight'] }}</p>
        <p class="card-text">Pokemon Types: {{ pokemon['types'] }}</p>
        <form action="{{ url_for('account.add_to_pokedex')}}" method="POST" novalidate>
          {{ poke_data_form.poke_name(value=pokemon['name']) }}
          {{ poke_data_form.hidden_tag() }}
          <div class="d-flex justify-content-end">
            {{ poke_data_form.submit(class="btn btn-mint fw-medium text-dark m-1", value='Add to PokeDex') }}
          </div>
        </form>
      </div>
    </div>
  </div>
  {% endif %}
  {% if not user and not pokemon %}
  <h3>No User or pokemon found for the search: {{ search }}</h3>
  {% endif %}
</div>
{% endblock content %}